export async function generateTrae3DSite(prompt: string, projectId: string): Promise<Record<string, string>> {
  const kind = /portfolio/i.test(prompt) ? "Portfolio" : /crypto|bitcoin/i.test(prompt) ? "Crypto" : /agency/i.test(prompt) ? "Agency" : /saas/i.test(prompt) ? "SaaS" : "Future";
  const title = kind === "SaaS" ? "Scale without the drag." : kind === "Portfolio" ? "Craft with intention." : kind === "Crypto" ? "Own the next block." : kind === "Agency" ? "Make the market look twice." : "Build what comes next.";
  const files: Record<string, string> = {};
  files["package.json"] = JSON.stringify({ name: `trae-site-${projectId.slice(0, 8)}`, private: true, scripts: { dev: "next dev", build: "next build", start: "next start" }, dependencies: { next: "14.2.15", react: "18.3.1", "react-dom": "18.3.1", three: "0.166.1", "@react-three/fiber": "8.16.8", "@react-three/drei": "9.108.3", "framer-motion": "11.3.19", gsap: "3.12.5" } }, null, 2);
  files["app/layout.tsx"] = `import type { Metadata } from "next";\nimport type { ReactNode } from "react";\nexport const metadata: Metadata = { title: "${kind} / Trae Builder", description: "A premium 3D experience", manifest: "/manifest.json", themeColor: "#8a2be2" };\nexport default function Layout({ children }: { children: ReactNode }) { return <html lang="en"><body>{children}<link rel="manifest" href="/manifest.json" /></body></html>; }`;
  files["components/Scene3D.tsx"] = `"use client";\nimport { Canvas } from "@react-three/fiber";\nimport { Environment, Float, OrbitControls, Sparkles, Stars } from "@react-three/drei";\nexport function Scene3D() { return <Canvas camera={{ position: [0, 0, 6], fov: 42 }}><color attach="background" args={["#070b17"]}/><ambientLight intensity={1.2}/><pointLight position={[3, 3, 2]} intensity={35} color="#8a2be2"/><Float speed={2} rotationIntensity={1.4} floatIntensity={2}><mesh><torusKnotGeometry args={[1.25, .34, 180, 28]}/><meshStandardMaterial color="#8a2be2" metalness={.8} roughness={.16} emissive="#312e81" emissiveIntensity={.8}/></mesh></Float><Sparkles count={90} scale={[6, 5, 4]} color="#67e8f9"/><Stars radius={30} depth={18} count={1800} factor={3}/><Environment preset="city"/><OrbitControls enableZoom={false} autoRotate autoRotateSpeed={.8}/></Canvas> }`;
  files["app/page.tsx"] = `"use client";\nimport { motion } from "framer-motion";\nimport { Scene3D } from "@/components/Scene3D";\nexport default function Page() { return <main className="shell"><header><b>✦ ${kind.toUpperCase()} / 01</b><nav>Work &nbsp; Studio &nbsp; Contact</nav><button>Start a project ↗</button></header><section className="hero"><motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }}><span>TRAЕ BUILDER — ${kind}</span><h1>${title}</h1><p>${prompt.replace(/`/g, "'")}</p><div><button>Explore the system →</button><button className="ghost">View case study</button></div></motion.div><div className="scene"><Scene3D/></div></section><section className="cards">{["Strategy that compounds.", "Interfaces with gravity.", "Motion that remembers."].map((x) => <article key={x}><i>✦</i><h2>{x}</h2><p>Purposeful systems, cinematic detail, and measurable momentum for the next chapter.</p></article>)}</section><style>{css}</style></main> }\nconst css = \\`*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 70% 25%,#281345,#080b17 45%,#04050b);color:#f4f1ff;font-family:Inter,system-ui,sans-serif}.shell{min-height:100vh;padding:26px 5vw 80px;overflow:hidden}header{max-width:1240px;margin:auto;display:flex;align-items:center;justify-content:space-between;padding:16px 20px;border:1px solid #ffffff1c;border-radius:20px;background:#11182775;backdrop-filter:blur(18px)}header b{font-size:12px;letter-spacing:.1em}nav{color:#b7b4cc;font-size:14px}button{border:0;border-radius:999px;padding:13px 20px;color:white;background:linear-gradient(135deg,#8a2be2,#4f46e5,#60a5fa);font-weight:700;cursor:pointer;box-shadow:0 18px 45px #8a2be244}.hero{max-width:1240px;margin:72px auto 0;display:grid;grid-template-columns:1fr 1fr;align-items:center;gap:30px}.hero span{color:#c4b5fd;font-size:12px;letter-spacing:.14em}.hero h1{font-size:clamp(4rem,8vw,8rem);line-height:.86;letter-spacing:-.08em;margin:20px 0}.hero p{color:#b7b4cc;line-height:1.7;max-width:530px;font-size:1.05rem}.hero button{margin:22px 12px 0 0}.ghost{background:#ffffff0d;box-shadow:none;border:1px solid #ffffff1c}.scene{height:580px;border-radius:32px;border:1px solid #ffffff1a;background:#0f172a80;overflow:hidden;box-shadow:0 30px 100px #0008}.cards{max-width:1240px;margin:50px auto 0;display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.cards article{padding:26px;border-radius:24px;background:#0f172a91;border:1px solid #ffffff14;backdrop-filter:blur(16px)}.cards i{color:#a78bfa;font-size:24px}.cards h2{font-size:1.4rem}.cards p{color:#a9a8bc;line-height:1.6}@media(max-width:850px){.hero,.cards{grid-template-columns:1fr}.scene{height:430px}nav{display:none}.hero h1{font-size:clamp(3.5rem,16vw,6rem)}}\\`;`;
  files["public/manifest.json"] = JSON.stringify({ name: "Trae Workspace", short_name: "Trae", start_url: "/", display: "standalone", background_color: "#000000", theme_color: "#8a2be2", icons: [{ src: "/icon.png", sizes: "512x512", type: "image/png" }] }, null, 2);
  files["public/sw.js"] = `self.addEventListener("install",()=>self.skipWaiting()); self.addEventListener("activate",e=>e.waitUntil(self.clients.claim())); self.addEventListener("fetch",e=>{if(e.request.method==="GET")e.respondWith(caches.match(e.request).then(x=>x||fetch(e.request)))})`;
  files["public/icon.png"] = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAF2GkzAAAAAXNSR0IArs4c6Q==";
  return files;
}
